//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("contestsModel", "SubmissionData_ibfk_1", "ContestInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContestRobot.DataAccess.ContestInfo), "SubmissionData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContestRobot.DataAccess.SubmissionData), true)]
[assembly: EdmRelationshipAttribute("contestsModel", "Responses_ibfk_1", "ContestInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContestRobot.DataAccess.ContestInfo), "Respons", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContestRobot.DataAccess.Respons), true)]

#endregion

namespace ContestRobot.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class contestsEntitiesConnection : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new contestsEntitiesConnection object using the connection string found in the 'contestsEntitiesConnection' section of the application configuration file.
        /// </summary>
        public contestsEntitiesConnection() : base("name=contestsEntitiesConnection", "contestsEntitiesConnection")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new contestsEntitiesConnection object.
        /// </summary>
        public contestsEntitiesConnection(string connectionString) : base(connectionString, "contestsEntitiesConnection")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new contestsEntitiesConnection object.
        /// </summary>
        public contestsEntitiesConnection(EntityConnection connection) : base(connection, "contestsEntitiesConnection")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ContestInfo> ContestInfoes
        {
            get
            {
                if ((_ContestInfoes == null))
                {
                    _ContestInfoes = base.CreateObjectSet<ContestInfo>("ContestInfoes");
                }
                return _ContestInfoes;
            }
        }
        private ObjectSet<ContestInfo> _ContestInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SubmissionData> SubmissionDatas
        {
            get
            {
                if ((_SubmissionDatas == null))
                {
                    _SubmissionDatas = base.CreateObjectSet<SubmissionData>("SubmissionDatas");
                }
                return _SubmissionDatas;
            }
        }
        private ObjectSet<SubmissionData> _SubmissionDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Respons> Responses
        {
            get
            {
                if ((_Responses == null))
                {
                    _Responses = base.CreateObjectSet<Respons>("Responses");
                }
                return _Responses;
            }
        }
        private ObjectSet<Respons> _Responses;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ContestInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContestInfoes(ContestInfo contestInfo)
        {
            base.AddObject("ContestInfoes", contestInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SubmissionDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubmissionDatas(SubmissionData submissionData)
        {
            base.AddObject("SubmissionDatas", submissionData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Responses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResponses(Respons respons)
        {
            base.AddObject("Responses", respons);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="contestsModel", Name="ContestInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ContestInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ContestInfo object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="entryURL">Initial value of the EntryURL property.</param>
        /// <param name="submissionURL">Initial value of the SubmissionURL property.</param>
        public static ContestInfo CreateContestInfo(global::System.Int32 id, global::System.String name, global::System.String entryURL, global::System.String submissionURL)
        {
            ContestInfo contestInfo = new ContestInfo();
            contestInfo.ID = id;
            contestInfo.Name = name;
            contestInfo.EntryURL = entryURL;
            contestInfo.SubmissionURL = submissionURL;
            return contestInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Desc
        {
            get
            {
                return _Desc;
            }
            set
            {
                OnDescChanging(value);
                ReportPropertyChanging("Desc");
                _Desc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Desc");
                OnDescChanged();
            }
        }
        private global::System.String _Desc;
        partial void OnDescChanging(global::System.String value);
        partial void OnDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartDate;
        partial void OnStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EntryURL
        {
            get
            {
                return _EntryURL;
            }
            set
            {
                OnEntryURLChanging(value);
                ReportPropertyChanging("EntryURL");
                _EntryURL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EntryURL");
                OnEntryURLChanged();
            }
        }
        private global::System.String _EntryURL;
        partial void OnEntryURLChanging(global::System.String value);
        partial void OnEntryURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubmissionURL
        {
            get
            {
                return _SubmissionURL;
            }
            set
            {
                OnSubmissionURLChanging(value);
                ReportPropertyChanging("SubmissionURL");
                _SubmissionURL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SubmissionURL");
                OnSubmissionURLChanged();
            }
        }
        private global::System.String _SubmissionURL;
        partial void OnSubmissionURLChanging(global::System.String value);
        partial void OnSubmissionURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SuccessPattern
        {
            get
            {
                return _SuccessPattern;
            }
            set
            {
                OnSuccessPatternChanging(value);
                ReportPropertyChanging("SuccessPattern");
                _SuccessPattern = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SuccessPattern");
                OnSuccessPatternChanged();
            }
        }
        private global::System.String _SuccessPattern;
        partial void OnSuccessPatternChanging(global::System.String value);
        partial void OnSuccessPatternChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FailurePattern
        {
            get
            {
                return _FailurePattern;
            }
            set
            {
                OnFailurePatternChanging(value);
                ReportPropertyChanging("FailurePattern");
                _FailurePattern = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FailurePattern");
                OnFailurePatternChanged();
            }
        }
        private global::System.String _FailurePattern;
        partial void OnFailurePatternChanging(global::System.String value);
        partial void OnFailurePatternChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("contestsModel", "SubmissionData_ibfk_1", "SubmissionData")]
        public EntityCollection<SubmissionData> SubmissionDatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SubmissionData>("contestsModel.SubmissionData_ibfk_1", "SubmissionData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SubmissionData>("contestsModel.SubmissionData_ibfk_1", "SubmissionData", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("contestsModel", "Responses_ibfk_1", "Respons")]
        public EntityCollection<Respons> Responses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Respons>("contestsModel.Responses_ibfk_1", "Respons");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Respons>("contestsModel.Responses_ibfk_1", "Respons", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="contestsModel", Name="Respons")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Respons : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Respons object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="contestID">Initial value of the ContestID property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        public static Respons CreateRespons(global::System.Int32 id, global::System.Int32 contestID, global::System.String user, global::System.DateTime created)
        {
            Respons respons = new Respons();
            respons.ID = id;
            respons.ContestID = contestID;
            respons.User = user;
            respons.Created = created;
            return respons;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContestID
        {
            get
            {
                return _ContestID;
            }
            set
            {
                OnContestIDChanging(value);
                ReportPropertyChanging("ContestID");
                _ContestID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContestID");
                OnContestIDChanged();
            }
        }
        private global::System.Int32 _ContestID;
        partial void OnContestIDChanging(global::System.Int32 value);
        partial void OnContestIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsSuccess
        {
            get
            {
                return _IsSuccess;
            }
            set
            {
                OnIsSuccessChanging(value);
                ReportPropertyChanging("IsSuccess");
                _IsSuccess = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSuccess");
                OnIsSuccessChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsSuccess;
        partial void OnIsSuccessChanging(Nullable<global::System.Boolean> value);
        partial void OnIsSuccessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RawResponse
        {
            get
            {
                return _RawResponse;
            }
            set
            {
                OnRawResponseChanging(value);
                ReportPropertyChanging("RawResponse");
                _RawResponse = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RawResponse");
                OnRawResponseChanged();
            }
        }
        private global::System.String _RawResponse;
        partial void OnRawResponseChanging(global::System.String value);
        partial void OnRawResponseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("contestsModel", "Responses_ibfk_1", "ContestInfo")]
        public ContestInfo ContestInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ContestInfo>("contestsModel.Responses_ibfk_1", "ContestInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ContestInfo>("contestsModel.Responses_ibfk_1", "ContestInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ContestInfo> ContestInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ContestInfo>("contestsModel.Responses_ibfk_1", "ContestInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ContestInfo>("contestsModel.Responses_ibfk_1", "ContestInfo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="contestsModel", Name="SubmissionData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SubmissionData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SubmissionData object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="contestID">Initial value of the ContestID property.</param>
        /// <param name="formData">Initial value of the FormData property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        public static SubmissionData CreateSubmissionData(global::System.Int32 id, global::System.String user, global::System.Int32 contestID, global::System.String formData, global::System.DateTime created)
        {
            SubmissionData submissionData = new SubmissionData();
            submissionData.ID = id;
            submissionData.User = user;
            submissionData.ContestID = contestID;
            submissionData.FormData = formData;
            submissionData.Created = created;
            return submissionData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContestID
        {
            get
            {
                return _ContestID;
            }
            set
            {
                OnContestIDChanging(value);
                ReportPropertyChanging("ContestID");
                _ContestID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContestID");
                OnContestIDChanged();
            }
        }
        private global::System.Int32 _ContestID;
        partial void OnContestIDChanging(global::System.Int32 value);
        partial void OnContestIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FormData
        {
            get
            {
                return _FormData;
            }
            set
            {
                OnFormDataChanging(value);
                ReportPropertyChanging("FormData");
                _FormData = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FormData");
                OnFormDataChanged();
            }
        }
        private global::System.String _FormData;
        partial void OnFormDataChanging(global::System.String value);
        partial void OnFormDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("contestsModel", "SubmissionData_ibfk_1", "ContestInfo")]
        public ContestInfo ContestInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ContestInfo>("contestsModel.SubmissionData_ibfk_1", "ContestInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ContestInfo>("contestsModel.SubmissionData_ibfk_1", "ContestInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ContestInfo> ContestInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ContestInfo>("contestsModel.SubmissionData_ibfk_1", "ContestInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ContestInfo>("contestsModel.SubmissionData_ibfk_1", "ContestInfo", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
